name: e2e Tests
on: [push, pull_request]
jobs:
  cypress-run:
    runs-on: ubuntu-16.04
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        run:
          npm ci
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm run start:demo:ci
          wait-on: 'http://localhost:3000'
          headless: true